### ISSUE TITLE
Mod greatly increases loading times

### ISSUE THREAD

**Issue by Queenofdragons6** [dgarroDC/ShipLogSlideReelPlayer#6]
This mod (and I did check that it was this mod) greatly increases how long it takes my computer to load the game's graphics, or just load in general. (Though whether that's specifically the result of this mod or something that happens with multiple mods active, I'm not sure, because it got somewhat better after disabling some other mods; before I did that, it had made the game crash.)

**Comment by dgarroDC** [comment]
What others mod did you disable that made it better?

**Comment by Queenofdragons6** [comment]
Power Failure and OW Smooth Thrust. Those two without this mod didn't cause delays.
I have more mods enabled, but those haven't given me issue.

**Comment by dgarroDC** [comment]
Ok thank you, I'll try to determine what's causing this

**Comment by dgarroDC** [comment]
I investigated this and found that I make a lot of unnecessary costly calls to `Resources.FindObjectsOfTypeAll` doing the initialization (many of them since release 1.2.2) that takes some seconds and is something I could easily fix. I was actually going to do that fix today.

However, this mod isn't supported anymore as explained in the [README](https://github.com/dgarroDC/ShipLogSlideReelPlayer/blob/main/README.md) because of today's OW update so I have no plans to fix this slowness, there are currently no reasons to use this mod in this state. If I ever do an upgraded reel player mod it would be drastically different from the current implementation so this particular issue wouldn't be there, so I'm closing this.

Thank you again for the report.

**Comment by dgarroDC** [comment]
I was wrong, reopening it

**Comment by Queenofdragons6** [comment]
Huh?

**Comment by dgarroDC** [comment]
The issue was still there in 2.0.0, that's why I reopened it, but it's now fixed in https://github.com/dgarroDC/ShipLogSlideReelPlayer/releases/tag/2.0.1, thank you for reporting this!
